// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Validations from "./validations";

function isValidPartialDate(_, _$1, year) {
  return !(year && !Validations.default(year));
}

export {
  isValidPartialDate ,
  
}
/* ./validations Not a pure module */
